# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: | 
        sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt install unzip google-chrome-stable
        python -m pip install --upgrade pip
        pip install selenium requests
        wget https://chromedriver.storage.googleapis.com/$(google-chrome --version|cut -b 15-26)/chromedriver_linux64.zip&&unzip chromedriver_linux64.zip&&sudo mv chromedriver /usr/local/bin/
    - name: Run code 
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      run: |
        python ./useselenium.py 
